from __future__ import annotations

from enum import StrEnum


class Categoria(StrEnum):
    SENIOR_MASCULINO = "SENIOR_MASCULINO"
    SENIOR_FEMENINO = "SENIOR_FEMENINO"
    MASTER_MASCULINO = "MASTER_MASCULINO"
    MASTER_FEMENINO = "MASTER_FEMENINO"
    JUNIOR_MASCULINO = "JUNIOR_MASCULINO"
    JUNIOR_FEMENINO = "JUNIOR_FEMENINO"
