from __future__ import annotations

from enum import StrEnum


class Categoria(StrEnum):
    SENIOR_MASCULINO = "SENIOR_MASCULINO"
    SENIOR_FEMENINO = "SENIOR_FEMENINO"
    MASTER_MASCULINO = "MASTER_MASCULINO"
    MASTER_FEMENINO = "MASTER_FEMENINO"
    JUVENIL_MASCULINO = "JUVENIL_MASCULINO"
    JUVENIL_FEMENINO = "JUVENIL_FEMENINO"
