from enum import StrEnum


class EstadoTorneo(StrEnum):
    CREADO = "CREADO"
    INSCRIPCION_ABIERTA = "INSCRIPCION_ABIERTA"
    PREPARACION = "PREPARACION"
    EJECUCION = "EJECUCION"
    PREMIACION = "PREMIACION"
    CERRADO = "CERRADO"
    CANCELADO = "CANCELADO"
